import { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import api from '../../services/api';
import { useAuth } from '../../context/AuthContext';

const tabs = [['overview','Overview'],['users','Users'],['products','Products'],['orders','Orders'],['categories','Categories']];

export default function AdminDashboard() {
  const { user, logout } = useAuth();
  const navigate = useNavigate();
  const [section,setSection]=useState('overview');
  async function signOut(){await logout();navigate('/',{replace:true});}
  return <div className="min-h-screen bg-slate-50 lg:flex">
    <aside className="bg-slate-950 text-white lg:flex lg:w-64 lg:flex-col"><div className="flex items-center justify-between px-5 py-5 lg:block"><Link to="/" className="text-lg font-bold">Market<span className="text-amber-300">place</span></Link><span className="rounded-full bg-white/10 px-3 py-1 text-xs text-slate-200 lg:mt-4 lg:inline-block">Admin console</span></div><nav className="flex gap-2 overflow-x-auto px-4 pb-4 lg:mt-8 lg:flex-col">{tabs.map(([key,label])=><button key={key} onClick={()=>setSection(key)} className={`whitespace-nowrap rounded-lg px-3 py-2.5 text-left text-sm font-medium ${section===key?'bg-amber-400 text-slate-950':'text-slate-300 hover:bg-white/10 hover:text-white'}`}>{label}</button>)}</nav><div className="hidden border-t border-white/10 p-5 lg:mt-auto lg:block"><p className="truncate text-sm font-medium">{user.name}</p><p className="mt-1 truncate text-xs text-slate-400">{user.email}</p><button onClick={signOut} className="mt-4 text-sm text-slate-300 hover:text-white">Sign out</button></div></aside>
    <main className="min-w-0 flex-1"><header className="flex items-center justify-between border-b border-slate-200 bg-white px-5 py-4 sm:px-8"><div><p className="text-xs font-semibold uppercase tracking-widest text-amber-800">Marketplace administration</p><h1 className="mt-1 text-xl font-bold">{tabs.find(([key])=>key===section)?.[1]}</h1></div><button onClick={signOut} className="rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold hover:bg-slate-50 lg:hidden">Sign out</button></header><div className="mx-auto max-w-7xl p-5 sm:p-8">{section==='overview'&&<Overview onOpenOrders={()=>setSection('orders')}/ >}{section==='users'&&<UsersPanel currentUserId={user.id}/ >}{section==='products'&&<ProductsPanel/>}{section==='orders'&&<OrdersPanel/>}{section==='categories'&&<CategoriesPanel/>}</div></main>
  </div>;
}

function Overview({onOpenOrders}){
  const [data,setData]=useState(null);const [error,setError]=useState('');
  useEffect(()=>{api.get('/admin/overview').then(({data:result})=>setData(result.data)).catch((err)=>setError(err.message||'Could not load analytics.'));},[]);
  if(error)return <p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-800">{error}</p>;
  const s=data?.summary;
  const cards=[['Total users',s?.totalUsers],['Buyers',s?.buyers],['Sellers',s?.sellers],['Active accounts',s?.activeUsers],['Suspended accounts',s?.suspendedUsers],['Products',s?.totalProducts],['Active products',s?.activeProducts],['Orders',s?.totalOrders],['Paid revenue',s?money(s.paidRevenue):null]];
  return <div className="space-y-7"><div><h2 className="text-2xl font-bold">Marketplace overview</h2><p className="mt-1 text-sm text-slate-600">Current marketplace activity and account totals.</p></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{cards.map(([label,value])=><div key={label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">{label}</p><p className="mt-3 text-3xl font-bold">{value??'—'}</p></div>)}</div>
    <div className="grid gap-6 xl:grid-cols-2"><MetricList title="Top products" values={data?.topProducts||[]} currency/><MetricList title="Top sellers" values={data?.topSellers||[]} currency/></div><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h3 className="font-semibold">Recent orders</h3><button onClick={onOpenOrders} className="text-sm font-semibold text-amber-800">View orders</button></div>{!data?<p className="mt-5 text-sm text-slate-500">Loading analytics…</p>:data.recentOrders.length===0?<p className="mt-5 text-sm text-slate-500">No orders yet.</p>:<div className="mt-4 overflow-x-auto"><table className="w-full min-w-[600px] text-left text-sm"><thead className="text-xs uppercase text-slate-500"><tr><th className="pb-2">Order</th><th className="pb-2">Buyer</th><th className="pb-2">Status</th><th className="pb-2">Total</th><th className="pb-2">Date</th></tr></thead><tbody>{data.recentOrders.map((order)=><tr key={order._id} className="border-t border-slate-100"><td className="py-3 font-medium">{order.orderNumber}</td><td className="py-3">{order.buyer?.name||'—'}</td><td className="py-3 capitalize">{order.status.replaceAll('_',' ')}</td><td className="py-3">{money(order.total,order.currency)}</td><td className="py-3 text-slate-500">{new Date(order.createdAt).toLocaleDateString()}</td></tr>)}</tbody></table></div>}</section></div>;
}

function MetricList({title,values,currency=false}){
  const max=Math.max(1,...values.map((item)=>item.units||0));
  return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="font-semibold">{title}</h3>{values.length===0?<p className="mt-4 text-sm text-slate-500">No delivered sales yet.</p>:<div className="mt-4 space-y-4">{values.map((item)=><div key={item._id}><div className="mb-1 flex justify-between gap-3 text-sm"><span className="truncate font-medium">{item.name}</span><span className="shrink-0 text-slate-500">{item.units} sold{currency&&item.gross?` · ${money(item.gross)}`:''}</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-amber-400" style={{width:`${Math.max(4,(item.units/max)*100)}%`}}/></div></div>)}</div>}</section>;
}

function UsersPanel({currentUserId}){
  const [users,setUsers]=useState([]);const [meta,setMeta]=useState({page:1,pages:1,total:0});const [page,setPage]=useState(1);const [search,setSearch]=useState('');const [role,setRole]=useState('');const [status,setStatus]=useState('');const [error,setError]=useState('');const [loading,setLoading]=useState(true);const [busy,setBusy]=useState('');
  async function load(){setLoading(true);try{const params=new URLSearchParams({page:String(page),limit:'20'});if(search.trim())params.set('search',search.trim());if(role)params.set('role',role);if(status)params.set('status',status);const {data}=await api.get(`/admin/users?${params}`);setUsers(data.data.users);setMeta(data.meta);}catch(err){setError(err.message||'Could not load users.');}finally{setLoading(false);}}
  useEffect(()=>{load();},[page,search,role,status]);
  async function update(id,patch){setBusy(id);setError('');try{await api.patch(`/admin/users/${id}`,patch);await load();}catch(err){setError(err.message||'Could not update account.');}finally{setBusy('');}}
  return <section><div><h2 className="text-2xl font-bold">User management</h2><p className="mt-1 text-sm text-slate-600">Manage buyer, seller, and administrator accounts.</p></div>{error&&<p role="alert" className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-800">{error}</p>}<div className="mt-5 flex flex-wrap gap-3"><input aria-label="Search users" value={search} onChange={(e)=>{setSearch(e.target.value);setPage(1);}} placeholder="Search name or email" className="min-w-56 flex-1 rounded-lg border border-slate-300 px-3 py-2 text-sm"/><select aria-label="Filter role" value={role} onChange={(e)=>{setRole(e.target.value);setPage(1);}} className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm"><option value="">All roles</option><option value="buyer">Buyer</option><option value="seller">Seller</option><option value="admin">Admin</option></select><select aria-label="Filter status" value={status} onChange={(e)=>{setStatus(e.target.value);setPage(1);}} className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm"><option value="">All status</option><option value="active">Active</option><option value="suspended">Suspended</option></select></div>
    <div className="mt-4 overflow-x-auto rounded-2xl border border-slate-200 bg-white shadow-sm"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">User</th><th className="px-4 py-3">Role</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Joined</th><th className="px-4 py-3">Actions</th></tr></thead><tbody>{loading?<tr><td colSpan="5" className="px-4 py-10 text-center text-slate-500">Loading users…</td></tr>:users.map((u)=><tr key={u._id} className="border-t border-slate-100"><td className="px-4 py-3"><p className="font-medium">{u.name}</p><p className="text-xs text-slate-500">{u.email}</p></td><td className="px-4 py-3"><select disabled={busy===u._id||u._id===currentUserId} value={u.role} onChange={(e)=>update(u._id,{role:e.target.value})} className="rounded-md border border-slate-300 bg-white px-2 py-1.5 text-xs"><option value="buyer">Buyer</option><option value="seller">Seller</option><option value="admin">Admin</option></select></td><td className="px-4 py-3"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${u.status==='active'?'bg-emerald-50 text-emerald-700':'bg-red-50 text-red-700'}`}>{u.status}</span></td><td className="px-4 py-3 text-slate-500">{new Date(u.createdAt).toLocaleDateString()}</td><td className="px-4 py-3"><button disabled={busy===u._id||u._id===currentUserId} onClick={()=>update(u._id,{status:u.status==='active'?'suspended':'active'})} className="text-xs font-semibold text-amber-800 hover:underline disabled:opacity-40">{u.status==='active'?'Suspend':'Activate'}</button></td></tr>)}</tbody></table></div><Pager page={page} meta={meta} setPage={setPage}/>
  </section>;
}

function ProductsPanel(){
  const [products,setProducts]=useState([]);const [meta,setMeta]=useState({page:1,pages:1,total:0});const [page,setPage]=useState(1);const [status,setStatus]=useState('');const [search,setSearch]=useState('');const [error,setError]=useState('');const [loading,setLoading]=useState(true);const [busy,setBusy]=useState('');
  async function load(){setLoading(true);try{const p=new URLSearchParams({page:String(page),limit:'20'});if(status)p.set('status',status);if(search.trim())p.set('search',search.trim());const {data}=await api.get(`/admin/products?${p}`);setProducts(data.data.products);setMeta(data.meta);}catch(err){setError(err.message||'Could not load products.');}finally{setLoading(false);}}
  useEffect(()=>{load();},[page,status,search]);
  async function update(productId,nextStatus){setBusy(productId);setError('');try{await api.patch(`/admin/products/${productId}`,{status:nextStatus});await load();}catch(err){setError(err.message||'Could not update product.');}finally{setBusy('');}}
  return <section><h2 className="text-2xl font-bold">Product moderation</h2><p className="mt-1 text-sm text-slate-600">Review listings and change visibility.</p>{error&&<p role="alert" className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-800">{error}</p>}<div className="mt-5 flex flex-wrap gap-3"><input aria-label="Search products" value={search} onChange={(e)=>{setSearch(e.target.value);setPage(1);}} placeholder="Search product listings" className="min-w-56 flex-1 rounded-lg border border-slate-300 px-3 py-2 text-sm"/><select aria-label="Filter listing status" value={status} onChange={(e)=>{setStatus(e.target.value);setPage(1);}} className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm"><option value="">All statuses</option><option value="draft">Draft</option><option value="active">Active</option><option value="archived">Archived</option></select></div><div className="mt-4 overflow-x-auto rounded-2xl border border-slate-200 bg-white shadow-sm"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Product</th><th className="px-4 py-3">Seller</th><th className="px-4 py-3">Price</th><th className="px-4 py-3">Stock</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Moderate</th></tr></thead><tbody>{loading?<tr><td colSpan="6" className="px-4 py-10 text-center text-slate-500">Loading products…</td></tr>:products.map((p)=><tr key={p._id} className="border-t border-slate-100"><td className="px-4 py-3"><p className="font-medium">{p.name}</p><p className="text-xs text-slate-500">{p.category?.name}</p></td><td className="px-4 py-3">{p.seller?.name||'—'}</td><td className="px-4 py-3">{money(p.price,p.currency)}</td><td className="px-4 py-3">{p.stock}</td><td className="px-4 py-3 capitalize">{p.status}</td><td className="px-4 py-3"><select disabled={busy===p._id} value={p.status} onChange={(e)=>update(p._id,e.target.value)} className="rounded-md border border-slate-300 bg-white px-2 py-1.5 text-xs"><option value="draft">Draft</option><option value="active">Active</option><option value="archived">Archived</option></select></td></tr>)}</tbody></table></div><Pager page={page} meta={meta} setPage={setPage}/></section>;
}

function OrdersPanel(){
  const [orders,setOrders]=useState([]);const [meta,setMeta]=useState({page:1,pages:1,total:0});const [page,setPage]=useState(1);const [status,setStatus]=useState('');const [selected,setSelected]=useState(null);const [error,setError]=useState('');const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);
  async function load(){setLoading(true);try{const p=new URLSearchParams({page:String(page),limit:'20'});if(status)p.set('status',status);const {data}=await api.get(`/admin/orders?${p}`);setOrders(data.data.orders);setMeta(data.meta);}catch(err){setError(err.message||'Could not load orders.');}finally{setLoading(false);}}
  useEffect(()=>{load();},[page,status]);
  useEffect(()=>{const handler=()=>{};window.addEventListener('admin:open-orders',handler);return()=>window.removeEventListener('admin:open-orders',handler);},[]);
  async function open(order){try{const {data}=await api.get(`/admin/orders/${order._id}`);setSelected(data.data.order);}catch(err){setError(err.message||'Could not load order details.');}}
  async function cancel(){if(!selected||!window.confirm(`Cancel unpaid order ${selected.orderNumber}? This cannot be undone.`))return;setBusy(true);setError('');try{await api.post(`/admin/orders/${selected._id}/cancel`);setSelected(null);await load();}catch(err){setError(err.message||'Could not cancel order.');}finally{setBusy(false);}}
  return <section><h2 className="text-2xl font-bold">Order monitoring</h2><p className="mt-1 text-sm text-slate-600">Review order status and open order details.</p>{error&&<p role="alert" className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-800">{error}</p>}<select aria-label="Filter order status" value={status} onChange={(e)=>{setStatus(e.target.value);setPage(1);}} className="mt-5 rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm"><option value="">All order statuses</option>{['pending','confirmed','processing','shipped','out_for_delivery','delivered','cancelled'].map((x)=><option key={x} value={x}>{x.replaceAll('_',' ')}</option>)}</select><div className="mt-4 overflow-x-auto rounded-2xl border border-slate-200 bg-white shadow-sm"><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Order</th><th className="px-4 py-3">Buyer</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Payment</th><th className="px-4 py-3">Total</th><th className="px-4 py-3">Details</th></tr></thead><tbody>{loading?<tr><td colSpan="6" className="px-4 py-10 text-center text-slate-500">Loading orders…</td></tr>:orders.map((o)=><tr key={o._id} className="border-t border-slate-100"><td className="px-4 py-3 font-medium">{o.orderNumber}</td><td className="px-4 py-3">{o.buyer?.name||'—'}</td><td className="px-4 py-3 capitalize">{o.status.replaceAll('_',' ')}</td><td className="px-4 py-3 capitalize">{o.payment?.status}</td><td className="px-4 py-3">{money(o.total,o.currency)}</td><td className="px-4 py-3"><button onClick={()=>open(o)} className="font-semibold text-amber-800 hover:underline">View</button></td></tr>)}</tbody></table></div><Pager page={page} meta={meta} setPage={setPage}/>
    {selected&&<div className="fixed inset-0 z-40 grid place-items-center bg-slate-950/40 p-4" role="presentation" onMouseDown={(e)=>{if(e.target===e.currentTarget)setSelected(null);}}><section role="dialog" aria-modal="true" aria-labelledby="order-modal-title" className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-6 shadow-xl"><div className="flex justify-between"><div><p className="text-xs font-semibold uppercase tracking-widest text-amber-800">Order details</p><h3 id="order-modal-title" className="mt-1 text-xl font-bold">{selected.orderNumber}</h3></div><button onClick={()=>setSelected(null)} aria-label="Close details" className="text-2xl leading-none text-slate-400">×</button></div><div className="mt-5 rounded-xl bg-slate-50 p-4 text-sm"><p className="font-semibold">{selected.shippingAddress.name}</p><p className="mt-1 leading-6 text-slate-600">{selected.shippingAddress.line1}, {selected.shippingAddress.city}, {selected.shippingAddress.region} {selected.shippingAddress.postalCode}, {selected.shippingAddress.country} · {selected.shippingAddress.phone}</p></div><div className="mt-5 space-y-3">{selected.items.map((item)=><div key={item._id} className="flex justify-between gap-4 border-b border-slate-100 pb-3 text-sm"><span>{item.name} × {item.quantity}<span className="ml-2 text-xs text-slate-500">({item.seller?.name})</span></span><span className="shrink-0">{money(item.unitPrice*item.quantity,selected.currency)} · {item.fulfillmentStatus.replaceAll('_',' ')}</span></div>)}</div><div className="mt-4 flex justify-between font-bold"><span>Order total</span><span>{money(selected.total,selected.currency)}</span></div>{selected.status==='pending'&&selected.payment?.status!=='paid'&&<button disabled={busy} onClick={cancel} className="mt-5 rounded-lg border border-red-200 px-4 py-2 text-sm font-semibold text-red-700 disabled:opacity-50">{busy?'Cancelling…':'Cancel unpaid pending order'}</button>}</section></div>}
  </section>;
}

function CategoriesPanel(){
  const [categories,setCategories]=useState([]);const [name,setName]=useState('');const [description,setDescription]=useState('');const [error,setError]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
  async function load(){try{const {data}=await api.get('/admin/categories');setCategories(data.data.categories);}catch(err){setError(err.message||'Could not load categories.');}}
  useEffect(()=>{load();},[]);
  async function create(e){e.preventDefault();setBusy(true);setError('');setMessage('');try{await api.post('/categories',{name,description});setName('');setDescription('');setMessage('Category created.');await load();}catch(err){setError(err.message||'Could not create category.');}finally{setBusy(false);}}
  async function toggle(category){setBusy(category._id);setError('');setMessage('');try{if(category.isActive)await api.delete(`/categories/${category._id}`);else await api.patch(`/categories/${category._id}`,{isActive:true});setMessage(category.isActive?'Category deactivated.':'Category activated.');await load();}catch(err){setError(err.message||'Could not update category.');}finally{setBusy(false);}}
  return <section><h2 className="text-2xl font-bold">Category management</h2><p className="mt-1 text-sm text-slate-600">Categories organize the public storefront and seller listings.</p>{error&&<p role="alert" className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-800">{error}</p>}{message&&<p role="status" className="mt-4 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800">{message}</p>}<form onSubmit={create} className="mt-5 grid gap-3 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:grid-cols-[1fr_2fr_auto]"><label className="text-sm font-medium">Name<input required minLength={2} maxLength={80} value={name} onChange={(e)=>setName(e.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2"/></label><label className="text-sm font-medium">Description<input maxLength={500} value={description} onChange={(e)=>setDescription(e.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2"/></label><button disabled={busy} className="self-end rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">Add category</button></form><div className="mt-4 space-y-3">{categories.map((category)=><article key={category._id} className="flex items-center justify-between gap-4 rounded-xl border border-slate-200 bg-white p-4"><div><h3 className="font-semibold">{category.name}</h3><p className="mt-1 text-xs text-slate-500">/{category.slug} · {category.isActive?'Active':'Inactive'}</p>{category.description&&<p className="mt-1 text-sm text-slate-600">{category.description}</p>}</div><button disabled={busy===category._id} onClick={()=>toggle(category)} className={`shrink-0 rounded-lg border px-3 py-2 text-xs font-semibold ${category.isActive?'border-slate-300 text-slate-700':'border-emerald-200 text-emerald-700'}`}>{category.isActive?'Deactivate':'Activate'}</button></article>)}</div></section>;
}

function Pager({page,meta,setPage}){return meta.pages>1?<div className="mt-5 flex items-center justify-center gap-4"><button disabled={page<=1} onClick={()=>setPage((p)=>p-1)} className="rounded-lg border border-slate-300 bg-white px-4 py-2 text-sm disabled:opacity-40">Previous</button><span className="text-sm text-slate-600">Page {page} of {meta.pages} · {meta.total} results</span><button disabled={page>=meta.pages} onClick={()=>setPage((p)=>p+1)} className="rounded-lg border border-slate-300 bg-white px-4 py-2 text-sm disabled:opacity-40">Next</button></div>:null;}
function money(value,currency='INR'){return new Intl.NumberFormat('en-IN',{style:'currency',currency:currency||'INR',maximumFractionDigits:0}).format(value||0);}
